Делал на VPS сервере (H100), не было времени настраивать jupyter notebook, поэтому запускал из терминала.


# Task 0
```
(edl) ubuntu@edl1:~/edl-week9$ python3 task0.py
loss=0.04599834233522415, accuracy=0.8768: : 10it [07:03, 38.32s/it]
Accuracy stabilized to 0.8768 at epoch 11
0.8809 10 0.04599834233522415
```

# Task 1
```
(edl) ubuntu@edl1-2:~/edl-week9$ python3 task1.py
loss=0.2514187693595886, accuracy=0.7511: : 16it [03:11, 11.20s/it]
Accuracy stabilized to 0.7511 at epoch 17
0.7585 16 0.2514187693595886
```


# Task 2
```
(edl) ubuntu@edl1-2:~/edl-week9$ python3 task2.py
loss=0.9624457359313965, accuracy=0.7909: : 15it [04:53, 18.28s/it]
Accuracy stabilized to 0.7909 at epoch 16
0.7827 15 0.9624457359313965
```


# Task 3
```
(edl) ubuntu@edl1-2:~/edl-week9$ python3 task3.py
loss=0.45746535062789917, accuracy=0.8041: : 10it [03:27, 18.78s/it]
Accuracy stabilized to 0.8041 at epoch 11
0.8035 10 0.45746535062789917
```
